//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 08:33:44 AM EEST 
//


package com.tieto.weather.model.soap;

import javax.xml.bind.annotation.XmlRegistry;

import com.tieto.weather.model.WeatherResponse;
import com.tieto.weather.model.rest.WeatherRESTResponse;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tieto.weather.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tieto.weather.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WeatherResponse }
     * 
     */
    public WeatherResponse createWeatherResponse() {
        return new WeatherRESTResponse();
    }

    /**
     * Create an instance of {@link WeatherObservationType }
     * 
     */
    public WeatherObservationType createWeatherObservationType() {
        return new WeatherObservationType();
    }

    /**
     * Create an instance of {@link WeatherRequest }
     * 
     */
    public WeatherRequest createWeatherRequest() {
        return new WeatherRequest();
    }

}
